### ISSUE TITLE
Replace MooX::Types::MooseLike::Base with Types::Standard

### ISSUE THREAD

**Issue by racke** [interchange/Interchange6-Demo-Shop#34]

**Comment by SysPete** [comment]
Perhaps we should create `Interchange6::Types` type library which includes all of the various `Type::Tiny` libraries we already use?

**Comment by SysPete** [comment]
Commit d83573ed0a42fa7643bcceb3614a26589360c2d9 removes `MooX::Types::MooseLike` in favour of `Dancer2::Core::Types` so we follow whatever Dancer does.

**Comment by racke** [comment]
Sound like a good idea. Thanks, @SysPete.
