### ISSUE TITLE
Session updates

### ISSUE THREAD

**Issue by racke** [interchange/Interchange6-Demo-Shop#35]
Quite some time is spent on session updates.

**Comment by SysPete** [comment]
I'm generally seeing 2 session updates per request which is unfortunate but since D1 session causes a flush to DB every time anything is set in the session there is little to be done. On my local Pg setup 2 writes takes just over 0.05s so I don't see this as anything worth attacking atm.

**Comment by SysPete** [comment]
Now we're using Dancer2 I only see session updates once per request. I suggest we close this issue.

**Comment by racke** [comment]
OK, done.
