### ISSUE TITLE
Shoppify logo

### ISSUE THREAD

**Issue by sbatschelet** [interchange/Interchange6-Demo-Shop#9]
http://www.shopify.com/ I know this was a joke but why not have our new ic6 logo I sent you?

**Comment by SysPete** [comment]
replaced with an old ic5 logo for now via commit 8605b7fe21463e9238ce196935bc97566a77aa96

**Comment by yure** [comment]
why not use ic6 logo?

**Comment by SysPete** [comment]
if someone can send me an ic6 logo I'll add it

**Comment by SysPete** [comment]
Closed by commit 9aab93f4d3c40655caaa67abb7c783827999856d
